version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exoplanet_dashboard
    ports:
      - "9000:9000" # Forward port 9000
    volumes:
      - .:/workspace # Mount the current directory into the container
    stdin_open: true # Keep the terminal open
    tty: true # Allocate a pseudo-TTY
    command: /bin/bash # Start the container in a terminal shell
