version: '3.8'

services:
  
  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - dev-net
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exoplanet_dashboard
    ports:
      - "9000:9000"
    volumes:
      - .:/workspace # Mount the current directory into the container
    stdin_open: true # Keep the terminal open
    tty: true # Allocate a pseudo-TTY
    command: /bin/bash # Start the container in a terminal shell
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydatabase
    networks:
      - dev-net

volumes:
  pgdata:

networks:
  dev-net:
    driver: bridge